version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    environment:
      -POSTGRES_PASSWORD=
      -POSTGRES_DB=nextcloud
      -POSTGRES_USER=nextcloud
    # env_file:
    #   - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html:z
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    # environment:
      -POSTGRES_PASSWORD=
      -POSTGRES_DB=nextcloud
      -POSTGRES_USER=nextcloud
    # env_file:
    #   - db.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
